### PR TITLE
Add metadata to Cloudfile and populate the S3 version with tags.

### PR DESCRIPTION
**Pull request by bseeger**
#### Issue tracking number 🔗

Part of the solution for MD Pilot issue: https://www.pivotaltracker.com/story/show/187339289

#### Description of change ✍️

This creates a new `metadata` field in the `Cloudfile` class. 
It also adds metadata about `tags` to the S3 implementation of the `S3CloudFileRepository.java`

#### Priority 🥇

I would need this pretty quickly - w/in a few days maybe?   :D

#### Effect on other applications using FFB 🌊

This should not break anything and should be invisible to any app that doesn't want extra metadata passed back about a file. 

#### ✅ Checklist before requesting a review

- [x] Does the new code follow [our preferred coding
  style](/intellij-settings/PlatformFlavoredGoogleStyle.xml)?
- [x] Does the code include javadocs, where necessary?
- [x] Have tests for this feature been added / updated?
- [x] Has the readme been updated?

### CODE REVIEW

**Comment by bseeger** [comment]
I need to update the readme.

**Comment by coltborg** [comment]
@bseeger, I'm not able to see the MD pivotal tracker board.

**Comment by bseeger** [comment]
Screenshot 2024-04-11 at 11 55 58 AM

Hi @coltborg this is a screen shot of the ticket. Basically we need to check the tags associated with the file in S3. This adds that ability to share any metadata the implementation (in this case S3) deems worth to share via the "metadata" field.

**Comment by coltborg** [comment]
> Screenshot 2024-04-11 at 11 55 58 AM
> 
> Hi @coltborg this is a screen shot of the ticket. Basically we need to check the tags associated with the file in S3. This adds that ability to share any metadata the implementation (in this case S3) deems worth to share via the "metadata" field.

Thank you for the context!

**Review by coltborg — APPROVED** [review]
approved

**Review by spokenbird — APPROVED** [review]

**Pull request merged**
