### PR TITLE
Updates error handling around S3 connection

### PR DESCRIPTION
**Pull request by bseeger**
This PR Addresses: https://www.pivotaltracker.com/story/show/185396051

### CODE REVIEW

**Comment by bseeger** [comment]
The code now returns a 500 Internal Server Error and a message: 

Screenshot 2023-06-16 at 5 13 09 PM

It will no longer exit the program.  Not sure if this is enough noise. 

This should maybe try to get to the developer facing error page, like the screen controller does when an error happens.

**Comment by tdooner** [comment]
Is there anything blocking this from being merged? We need this in order to launch as this represents a serious Denial of Service vulnerability.

**Comment by bseeger** [comment]
Hi @tdooner are you okay with what it's doing now?  
The above error message is display and this is in the logs: 
Screenshot 2023-06-21 at 3 44 22 PM


If this looks good, then I think we can merge.

**Comment by tdooner** [comment]
Anything's better than what's currently in there! Your improvement looks good, too.

**Review by coltborg — APPROVED** [review]
Code looks good and was able to confirm locally.

Screenshot 2023-06-21 at 4 35 46 PM

**Pull request merged**
