### PR TITLE
Moves setup.sh script into script directory and updates readme.

### PR DESCRIPTION
**Pull request by bseeger**

### CODE REVIEW

**Comment by bseeger** [comment]
Mirroring the addition of the scripts directory in the starter app.  Not sure if we should do this though. Thoughts?

**Comment by vrajmohan** [comment]
Do you expect many more scripts to be added? If so, IMO, it's worth creating a `scripts` directory. It may not be worth it for a couple of scripts.

**Comment by bseeger** [comment]
I don't anticipate more scripts right now, so leaving it in the main repo is fine with me.  Wasn't sure if it was worth having the directory or not (sort of aligning the repos).

**Comment by bseeger** [comment]
Closing as not really necessary.

**Pull request closed without merging**
