### PR TITLE
Adds onPost and crossValidationAction

### PR DESCRIPTION
**Pull request by bseeger**
Adds more actions to provide SNE ability to write custom code for pre validation as well as validation. 

https://www.pivotaltracker.com/story/show/184576570

### CODE REVIEW

**Comment by bseeger** [comment]
Please don't add any more changes til I can get my new stuff up here. I have a lot of changes and we'll duplicate work if others are working on it. 

Thanks!!

**Comment by sree-cfa** [comment]
> Please don't add any more changes til I can get my new stuff up here. I have a lot of changes and we'll duplicate work if others are working on it.
> 
> Thanks!!

Got it! Sorry about that 😅

**Comment by bseeger** [comment]
@sree-cfa No worries. I was concerned that the rebase would be hard, but actually, it turned out okay.  :) I was worried, though that others might have different, less easy merges coming.   I hate long running branches.

**Comment by sree-cfa** [comment]
@bseeger Could we do the `beforeDisplay` action stuff in a separate PR to merge it sooner (so we can use it for encryption)? Or do you think it's better to complete all of the action work here?

**Comment by bseeger** [comment]
@sree-cfa  If you want to pull it into another PR, I'd be fine with that.   I was working on adding tests -- would you have time to add a test or two for that action as you go?

**Comment by sree-cfa** [comment]
For sure!

**Comment by bseeger** [comment]
Great! :)

**Pull request merged**
